[package]
name = "ironcore-documents"
description = "A library for working with IronCore Labs documents and header formats."
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
protobuf = { version = "3.3", features = [ "with-bytes" ] }
ring = { version = "0.17", features = [ "std" ] }
thiserror = "1"

[build-dependencies]
protobuf-codegen = "3.3"
